### ISSUE TITLE
dataset format 

### ISSUE THREAD

**Issue by robinjoe93** [calmisential/Basic_CNNs_TensorFlow2.0#1]
could you supply the sample of dataset format for mobilenet

**Comment by calmiLovesAI** [comment]
Just follow the instructions in READMD.md, it's suitable for all networks included in the repository.

**Comment by robinjoe93** [comment]
> Just follow the instructions in READMD.md, it's suitable for all networks included in the repository.

I successed run the programmer
thanks for your response
