### ISSUE TITLE
how can I test smple image without tfrecord ?

### ISSUE THREAD

**Issue by angryhen** [calmisential/Basic_CNNs_TensorFlow2.0#4]

**Comment by calmiLovesAI** [comment]
If you want to test .jpg, .jpeg type pictures, you need to use tf.io.read_file() function to read the picture path, then pass the result to load_and_preprocess_image() function to get tensor type data, and finally enter it into the network. Use tf.argmax() to get the prediction from the output.

**Comment by angryhen** [comment]
thanks very much, I get it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "calmisential"<notifications@github.com&gt;; 
发送时间: 2019年12月4日(星期三) 上午9:49
收件人: "calmisential/Basic_CNNs_TensorFlow2"<Basic_CNNs_TensorFlow2@noreply.github.com&gt;; 
抄送: "copain"<982830737@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [calmisential/Basic_CNNs_TensorFlow2] how can I test smple image without tfrecord ? (#4)




If you want to test .jpg, .jpeg type pictures, you need to use tf.io.read_file() function to read the picture path, then pass the result to load_and_preprocess_image() function to get tensor type data, and finally enter it into the network. Use tf.argmax() to get the prediction from the output.
