### ISSUE TITLE
I got this error when I run evaluate.py?

### ISSUE THREAD

**Issue by angryhen** [calmisential/Basic_CNNs_TensorFlow2.0#5]
I'm sure that the model had been save by train.py.

`    /home/du/Desk/my_project/Basic_CNNs_TensorFlow2/evaluate.py:28 test_step  *
        predictions = model(images, training=False)

    TypeError: '_UserObject' object is not callable
`

**Comment by calmiLovesAI** [comment]
This might be the bug of tensorflow2.0.0, you can just only save and load weights instead of the whole model.
